# Generated by Django 6.0.1 on 2026-04-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_add_hot_raw_browse_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedProteinSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.CharField(db_index=True, max_length=255)),
                ('protein_id', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20)),
                ('protein_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('protein_length', models.PositiveIntegerField(default=0)),
                ('gene_symbol_label', models.TextField(blank=True)),
                ('methods_label', models.TextField(blank=True)),
                ('repeat_residues_label', models.TextField(blank=True)),
                ('coordinate_label', models.TextField(blank=True)),
                ('protein_length_label', models.TextField(blank=True)),
                ('source_runs_count', models.PositiveIntegerField(default=0)),
                ('source_taxa_count', models.PositiveIntegerField(default=0)),
                ('source_proteins_count', models.PositiveIntegerField(default=0)),
                ('source_repeat_calls_count', models.PositiveIntegerField(default=0)),
                ('residue_groups_count', models.PositiveIntegerField(default=0)),
                ('collapsed_repeat_calls_count', models.PositiveIntegerField(default=0)),
                ('representative_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.protein')),
                ('representative_repeat_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.repeatcall')),
            ],
            options={
                'ordering': ['accession', 'protein_name', 'protein_id', 'method'],
            },
        ),
        migrations.CreateModel(
            name='MergedProteinOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_proteins_count', models.PositiveIntegerField(default=0)),
                ('source_repeat_calls_count', models.PositiveIntegerField(default=0)),
                ('residue_groups_count', models.PositiveIntegerField(default=0)),
                ('collapsed_repeat_calls_count', models.PositiveIntegerField(default=0)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_protein_occurrences', to='browser.pipelinerun')),
                ('representative_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.protein')),
                ('representative_repeat_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.repeatcall')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_protein_occurrences', to='browser.taxon')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='browser.mergedproteinsummary')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'summary__accession', 'summary__protein_name', 'summary__protein_id'],
            },
        ),
        migrations.CreateModel(
            name='MergedResidueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.CharField(db_index=True, max_length=255)),
                ('protein_id', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20)),
                ('repeat_residue', models.CharField(db_index=True, max_length=16)),
                ('protein_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('protein_length', models.PositiveIntegerField(default=0)),
                ('gene_symbol_label', models.TextField(blank=True)),
                ('methods_label', models.TextField(blank=True)),
                ('coordinate_label', models.TextField(blank=True)),
                ('protein_length_label', models.TextField(blank=True)),
                ('start', models.PositiveIntegerField(default=0)),
                ('end', models.PositiveIntegerField(default=0)),
                ('length', models.PositiveIntegerField(default=0)),
                ('length_label', models.TextField(blank=True)),
                ('normalized_purity', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('purity_label', models.TextField(blank=True)),
                ('source_runs_count', models.PositiveIntegerField(default=0)),
                ('source_taxa_count', models.PositiveIntegerField(default=0)),
                ('source_proteins_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('representative_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.protein')),
                ('representative_repeat_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.repeatcall')),
            ],
            options={
                'ordering': ['accession', 'protein_name', 'protein_id', 'method', 'repeat_residue'],
            },
        ),
        migrations.CreateModel(
            name='MergedResidueOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_proteins_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_residue_occurrences', to='browser.pipelinerun')),
                ('representative_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.protein')),
                ('representative_repeat_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.repeatcall')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_residue_occurrences', to='browser.taxon')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='browser.mergedresiduesummary')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'summary__accession', 'summary__protein_name', 'summary__protein_id', 'summary__repeat_residue'],
            },
        ),
        migrations.AddIndex(
            model_name='mergedproteinsummary',
            index=models.Index(fields=['accession', 'protein_name', 'id'], name='brw_mgprot_acc_name_id'),
        ),
        migrations.AddIndex(
            model_name='mergedproteinsummary',
            index=models.Index(fields=['protein_name', 'accession', 'id'], name='brw_mgprot_name_acc_id'),
        ),
        migrations.AddIndex(
            model_name='mergedproteinsummary',
            index=models.Index(fields=['method', 'accession', 'protein_name'], name='brw_mgprot_method_acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='mergedproteinsummary',
            constraint=models.UniqueConstraint(fields=('accession', 'protein_id', 'method'), name='browser_mgprot_unique_acc_pid_method'),
        ),
        migrations.AddIndex(
            model_name='mergedproteinoccurrence',
            index=models.Index(fields=['pipeline_run', 'taxon', 'summary'], name='brw_mgprotocc_run_tax_sum_idx'),
        ),
        migrations.AddIndex(
            model_name='mergedproteinoccurrence',
            index=models.Index(fields=['summary', 'pipeline_run'], name='brw_mgprotocc_sum_run_idx'),
        ),
        migrations.AddIndex(
            model_name='mergedproteinoccurrence',
            index=models.Index(fields=['taxon', 'summary'], name='brw_mgprotocc_tax_sum_idx'),
        ),
        migrations.AddConstraint(
            model_name='mergedproteinoccurrence',
            constraint=models.UniqueConstraint(fields=('summary', 'pipeline_run', 'taxon'), name='browser_mgprotocc_unique_sum_run_tax'),
        ),
        migrations.AddIndex(
            model_name='mergedresiduesummary',
            index=models.Index(fields=['accession', 'protein_name', 'id'], name='brw_mgres_acc_name_id'),
        ),
        migrations.AddIndex(
            model_name='mergedresiduesummary',
            index=models.Index(fields=['protein_name', 'accession', 'id'], name='brw_mgres_name_acc_id'),
        ),
        migrations.AddIndex(
            model_name='mergedresiduesummary',
            index=models.Index(fields=['method', 'repeat_residue', 'accession', 'id'], name='brw_mgres_method_res_acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='mergedresiduesummary',
            constraint=models.UniqueConstraint(fields=('accession', 'protein_id', 'method', 'repeat_residue'), name='browser_mgres_unique_acc_pid_method_res'),
        ),
        migrations.AddIndex(
            model_name='mergedresidueoccurrence',
            index=models.Index(fields=['pipeline_run', 'taxon', 'summary'], name='brw_mgresocc_run_tax_sum_idx'),
        ),
        migrations.AddIndex(
            model_name='mergedresidueoccurrence',
            index=models.Index(fields=['summary', 'pipeline_run'], name='brw_mgresocc_sum_run_idx'),
        ),
        migrations.AddIndex(
            model_name='mergedresidueoccurrence',
            index=models.Index(fields=['taxon', 'summary'], name='brw_mgresocc_tax_sum_idx'),
        ),
        migrations.AddConstraint(
            model_name='mergedresidueoccurrence',
            constraint=models.UniqueConstraint(fields=('summary', 'pipeline_run', 'taxon'), name='browser_mgresocc_unique_sum_run_tax'),
        ),
    ]
