# Generated by Django 6.0.1 on 2026-04-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0014_pipelinerun_canonical_sync_batch_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessioncallcount",
            options={
                "ordering": ["pipeline_run__run_id", "assembly_accession", "method", "repeat_residue"],
                "verbose_name": "imported accession call-count row",
                "verbose_name_plural": "imported accession call-count rows",
            },
        ),
        migrations.AlterModelOptions(
            name="accessionstatus",
            options={
                "ordering": ["pipeline_run__run_id", "assembly_accession"],
                "verbose_name": "imported accession status row",
                "verbose_name_plural": "imported accession status rows",
            },
        ),
        migrations.AlterModelOptions(
            name="downloadmanifestentry",
            options={
                "ordering": ["pipeline_run__run_id", "batch__batch_id", "assembly_accession"],
                "verbose_name": "imported download-manifest row",
                "verbose_name_plural": "imported download-manifest rows",
            },
        ),
        migrations.AlterModelOptions(
            name="genome",
            options={
                "ordering": ["pipeline_run__run_id", "accession", "genome_id"],
                "verbose_name": "imported genome observation",
                "verbose_name_plural": "imported genome observations",
            },
        ),
        migrations.AlterModelOptions(
            name="normalizationwarning",
            options={
                "ordering": ["pipeline_run__run_id", "batch__batch_id", "warning_code", "assembly_accession"],
                "verbose_name": "imported normalization warning",
                "verbose_name_plural": "imported normalization warnings",
            },
        ),
        migrations.AlterModelOptions(
            name="protein",
            options={
                "ordering": ["pipeline_run__run_id", "protein_name", "protein_id"],
                "verbose_name": "imported protein observation",
                "verbose_name_plural": "imported protein observations",
            },
        ),
        migrations.AlterModelOptions(
            name="repeatcall",
            options={
                "ordering": ["pipeline_run__run_id", "protein__protein_name", "start", "call_id"],
                "verbose_name": "imported repeat-call observation",
                "verbose_name_plural": "imported repeat-call observations",
            },
        ),
        migrations.AlterModelOptions(
            name="runparameter",
            options={
                "ordering": ["pipeline_run__run_id", "method", "repeat_residue", "param_name"],
                "verbose_name": "imported run parameter",
                "verbose_name_plural": "imported run parameters",
            },
        ),
        migrations.AlterModelOptions(
            name="sequence",
            options={
                "ordering": ["pipeline_run__run_id", "sequence_name", "sequence_id"],
                "verbose_name": "imported sequence observation",
                "verbose_name_plural": "imported sequence observations",
            },
        ),
    ]
