# Generated by Django 6.0.1 on 2026-04-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0015_historical_layer_model_labels"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MergedProteinOccurrence",
        ),
        migrations.DeleteModel(
            name="MergedResidueOccurrence",
        ),
        migrations.DeleteModel(
            name="MergedProteinSummary",
        ),
        migrations.DeleteModel(
            name="MergedResidueSummary",
        ),
    ]
