# Generated by Django 6.0.1 on 2026-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0023_download_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(db_index=True, max_length=64)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('scope_params', models.JSONField(default=dict)),
                ('catalog_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['build_type', 'scope_key', 'catalog_version'], name='browser_pldbuild_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('build_type', 'scope_key', 'catalog_version'), name='browser_pldbuild_unique')],
            },
        ),
    ]
