# Generated by Django 5.2.13 on 2026-04-29 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_catalogversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('receiving', 'Receiving'), ('received', 'Received'), ('extracting', 'Extracting'), ('ready', 'Ready'), ('queued', 'Queued'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='receiving', max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('chunk_size_bytes', models.PositiveIntegerField(default=8388608)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('received_chunks', models.JSONField(blank=True, default=list)),
                ('publish_root', models.CharField(blank=True, max_length=500)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_runs', to='imports.importbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
